// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    QBtn: typeof import('quasar')['QBtn']
    QDrawer: typeof import('quasar')['QDrawer']
    QHeader: typeof import('quasar')['QHeader']
    QItemLabel: typeof import('quasar')['QItemLabel']
    QLayout: typeof import('quasar')['QLayout']
    QList: typeof import('quasar')['QList']
    QPage: typeof import('quasar')['QPage']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
